name: trpc_client
description: A minimal trpc client for Dart and Flutter.
version: 0.3.4
repository: https://github.com/wosherco/trpc-client-dart
issue_tracker: https://github.com/wosherco/trpc-client-dart/issues
homepage: https://github.com/wosherco/trpc-client-dart

environment:
  sdk: ^3.4.0

dependencies:
  build: ^2.4.1
  http: ^1.2.1
  queue: ^3.1.0+2
  source_gen: ^1.5.0
  analyzer: '>=5.2.0 <7.0.0'
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.7.1
  

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
